language: scala

scala:
- 2.12.1
sudo: false

jdk:
- oraclejdk8

env:
- PROJECT_DIR=ShortUrlService

script:
- cd $PROJECT_DIR; sbt ++$TRAVIS_SCALA_VERSION assembly

before_deploy:
- ls target/build

deploy:
  - provider: s3
    access_key_id: "AKIAJFK4KXOVHLR3USNA"
    secret_access_key: 
      secure: "GIFSXtzGWJe6xgMptxeAITMuMVfnIdFkpLJG9NqBE0+Ef+4fCW6RjeA9tx+g3QGJeSIn8EK0rv8HCm2xr4AgOP2YVdfQZt4ViuCrFo55rtqv+TP5aru1fBr/5MB48r8fRSjrrCINjvPFDEVbB5Xp+Kub9bFvUiYQtTkYn0BitHRZn8D/mXIiRYujpF5beumwTm4wmOoXUi7c3NvUjxpJk/JAsBUvVVGyTXcfWI7gWvxEpPh+qNZ7vVMx7k7JXYYprESF8LRvPWYw1RssOKFvBSMSUrThzj1HcW/P5R9s27hngV1u1XRA7IVwgR0wgHYMPCl5Ex6V7XrLqIrmVyyrz9BHAuCsWoaJMS7xd6SD6rrjp+TXomV8T3g2X7O6M6b318aj+bHJpMcy2qBAaJji1lkk+rmrSRdGvKP7Ls1LGtxAgFv4fXwryV7XU4Sl/R90serbATL5OBjuKRuH2wJruiULZyLlHzo41dFDTAmsM/L72HAPUgArkNLpernuXiEtPkj3vfxFaLbkqi16BihtThBD1TcMOA8kxeN7S1wmu2BsMKHsg1LvPptTaQ3BU9JiCGKu/JyayPu0cpb1U7rVLpx2fdc501D5Fm2yLVxYi3JPy8T9ZH7m3gv0YCYYLbPGcMtXlWsOdGE/fz2ZXCLgtlN7i8JXYPZ0EPKFgSpcLC4="
    local_dir: target/build
    skip_cleanup: true
    bucket: test.deployment


cache:
  directories:
  - "$HOME/.sbt/0.13/dependency"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"

  
before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
