language: scala

scala:
- 2.12.1
sudo: false

jdk:
- oraclejdk8

env:
- PROJECT_DIR=ShortUrlService

script:
- cd $PROJECT_DIR; sbt ++$TRAVIS_SCALA_VERSION assembly

before_deploy:
- ls target/build

deploy:
  access_key_id:
    secure: tX20GOFeqAXN712aX8wxHjyrh3skxVxuV+WICpAJ1lecIjABQLTMJJwcWaV4/n3kHISD9VTnCrgoNvrOd/RCraRG83YZtZstqy2GKQHVY8GJy6yQ40XXizx+SLNpFn6eRKyhHSK6+PEre/1mPVA9m2/SEEaMuj5ld8pYPdx4sPSOU7VFDStEZtSXADEnfm6MxZRIIcl/nxob4izjCgMxxmQksRVePNwKWFC7fCNuzjedT5YMOdKiwR2l5363J/2IUCdp9W9W7tkMr/uZ6k5fg0GUTcjGdPbrSLCiNBlQ0JJ3i3Z0KrnwU1FsfbUDKWWb+nPYdKg7C7Fuc5Gd3o/sw/PpPoK3b7otDWMIGzl2c0KxX7WUJz7W17q9mAsY66eyc/TNfOMVtmaoAH/WbDqfBH3WLQwmAu2wrDl7csVIXxeN2HkI5dwvCe42RbFhAoyFgQs2DWC8jYxbhaCu/+SDRSg2igJHA/KaxMc5pxzWwAAcOWv341vKL4izXM3em92rxCXtGXBwdUchhqutGLXzLRMjC4/j8QQPXEVFjXZYrml6DY0FVtTcc6wTmYq3ykFd06gRAf541OH6IdpxrLswMFP4HZxJbTOOJZg25rKAchXWxJWxuxxyl3j2tTH3rzokz4DgIqj4tejUvXytqcqGEdM1Nc1IAhwcCMb6ewVi4z4=
  secret_access_key:
    secure: rJo/1R4u1DKqczjLgKpj2CbNMgYJw7b4Gho4ZSKBXdkdqZVTw39APx7zactqlrRNqhsKDLkW3y5RcbMdrMy5mQV/eH1Dc+ezBsy03zwTy3qePIDVHS4HS+APCwLFsVNsSGL9wYs8WmpGzTQmiMO+nyu5mVeg0bCW47i8mclj/SXUY/u94Wq4gj3n0cgUfrulN6w0lifEWtCW2JX7A1L0tHZxY3zG9J4TFJqGoH1Lq8ltpjSc6MiQzYaSES+S3SEuWFa/bhiUmXxAoSw5tdCyMJVhePNzJ6BSk8snX98dZA0ajMnvrCAllXMxKFn/3qOqf0wexMh8757GbKdAPS4vIqfhp8XX96jQ51+QCOPUTdTB0gug5G8FLAJZTuFcTrDt1JWCOGPktsb2dSMtvl2J8hG30tPkRA3HcJrpafC0D5d9ESH5qrl2L7MSV/N4oyW8GG1mYbdbds+EUIXWlDPvG4b8xZwCE7tNmjm6YL1FaAwHdi3kc3JqgcdV/So09FuaI6OJ6l4CEfqENq3Wph2pJWvaOhlCJHXO9HOjzHhFKRhoDUicei8dk0NLe9Ae4boriP6bRvoWflUqCFfmAb+SAY+Np8P2TBy7j/ef4WnyTmOqm2VdR3XmDDuBoJBfn5pkZPe5zKxwG7qTkLq5eO1cH50zVh4oEYWn9KSHoG7hqH0=
  local_dir: target/build
  skip_cleanup: true
  bucket: test.deployment


cache:
  directories:
  - "$HOME/.sbt/0.13/dependency"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"

  
before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
